# Generated by Django 2.1.1 on 2018-11-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('ngo_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('social_cause', models.CharField(max_length=1000)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.City')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.State'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.State'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.City'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aca.State'),
        ),
    ]
